### ISSUE TITLE
localStrageでキャッシュを利かす方法

### ISSUE THREAD

**Issue by yunoda-3DCG** [VRHIKKY/VketCloudSDK_Documents#7]
ログインボーナスとかに使えるかもな機能について

**Comment by Kondo-Totori** [comment]
JavaScriptにて下記を入力することで可能です。

・キーの設定
localStorage.setItem('キー', '値');

- 配列で設定する場合
var array = [];
var obj = {
  'キー1': '値1',
  'キー2': '値2'
};
array.push(obj);

var setjson = JSON.stringify(obj);
localStorage.setItem('キー', setjson);

・キーの取得
localStorage.getItem('キー');

- 配列を取得する場合
var getjson = localStorage.getItem('キー');
var obj = JSON.parse(getjson);

・キーの削除
localStorage.removeItem('キー');

・キー状態の初期化
localStorage.clear()

-----

Tips
キーはString型で取得します。数字を扱う場合、対応する型に変換する必要があります。
キーが存在しない場合、nullとなります。
-----

実装例:アイテム取得を記録、取得状況を起動時に確認

//アイテム総数
itemTotal = 10;

//アイテム取得時 (itemNumberはcallJsのtextで渡すものとする)
function item_get(itemNumber) {
    localStorage.setItem('itemGet_' + itemNumber, 'true');
}

//起動時
function item_check() {
    for(let i = 0; i<itemTotal; i++){
        if(localStprage.getItem('itemGet_' + i) != null) {
            //アイテムを取得している時の処理
        }
    }
}

**Comment by ra9g16** [comment]
@Kondo-Totori 
JavaScriptが社外版SDKでは使わない想定でいるので、追加不要
